trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'ed1ab223-9ba7-44a6-b679-6a9ae0d307d8'
  imageRepository: 'shayanhasankhandevopsprojectbackend'
  containerRegistry: 'devopsprojectfast.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

jobs:
- job: Build_and_Push
  displayName: Build and push stage
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.19.0' # Specify the Node.js version you want to use
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)
